[theme]
primaryColor = "#DC143C"
backgroundColor = "#F5F5DC"
secondaryBackgroundColor = "#E8E8D0"
textColor = "#000000"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
